[package]
name = "mod_rewrite"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
once_cell = "1.21.3"
percent-encoding = "2.3.1"
regex-automata = "0.4.9"
thiserror = "2.0.12"
unicase = "2.8.1"
