[package]
name = "mod_rewrite"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
derive_more = { version = "2.0.1", features = ["display", "error", "from"] }
once_cell = "1.21.3"
regex = "1.11.1"
unicase = "2.8.1"
